stages:
  - build

variables:
  V: "0"
  MAKEFLAGS: "-j8 --no-keep-going"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
   # add gitlab ssh key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    # Create esp-rainmaker-bins-${CI_JOB_ID}/ dir (to copy binaries into for artifacts)
    - mkdir -p $CI_PROJECT_DIR/esp-rainmaker-bins-${CI_JOB_ID}

.build_all_examples: &build_all_examples
# - pip install --upgrade idf-component-manager
- for EXAMPLE in $EXAMPLES; do
- cd $CI_PROJECT_DIR/examples/$EXAMPLE
- echo Building $EXAMPLE
- for TARGET in $EXAMPLE_TARGETS; do
- echo Building for $TARGET
- if [ "$TARGET" = "esp32c5" ]; then
-   echo "ESP32-C5 detected, adding --preview flag."
-   PREVIEW_FLAG="--preview"
- fi
- idf.py $PREVIEW_FLAG set-target $TARGET
- idf.py build
- done
- echo Build Complete for $EXAMPLE
- done

.build_template:
  stage: build
  image: espressif/idf:latest
  tags:
    - build
  variables:
    PEDANTIC_FLAGS: "-Werror=deprecated-declarations -Wno-error=cpp"
    EXTRA_CFLAGS: "${PEDANTIC_FLAGS}"
    EXTRA_CXXFLAGS: "${PEDANTIC_FLAGS}"
    EXAMPLE_TARGETS: "esp32"
    EXAMPLES: "mqtt/tls_mutual_auth http/http_mutual_auth jobs thing_shadow fleet_provisioning/fleet_provisioning_with_csr"
  script:
    - *build_all_examples

build_idf_v5.1:
  extends: .build_template
  image: espressif/idf:release-v5.1
  variables:
    EXAMPLE_TARGETS: "esp32 esp32c3 esp32s2 esp32s3 esp32c2 esp32c6"

build_idf_v5.2:
  extends: .build_template
  image: espressif/idf:release-v5.2
  variables:
    EXAMPLE_TARGETS: "esp32 esp32c3 esp32s2 esp32s3 esp32c2 esp32c6"

build_idf_v5.3:
  extends: .build_template
  image: espressif/idf:release-v5.3
  variables:
    EXAMPLE_TARGETS: "esp32 esp32c3 esp32s2 esp32s3 esp32c2 esp32c6"

build_idf_v5.4:
  extends: .build_template
  image: espressif/idf:release-v5.4
  variables:
    EXAMPLE_TARGETS: "esp32 esp32c3 esp32s2 esp32s3 esp32c2 esp32c6"

build_idf_v5.5:
  extends: .build_template
  image: espressif/idf:release-v5.5
  variables:
    EXAMPLE_TARGETS: "esp32 esp32c3 esp32s2 esp32s3 esp32c2 esp32c6 esp32c5"
